server:
  port: 8888


spring:
  application:
    name: service.config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: file:///D:/source/[MZ_HEALTHCARE]/git-local-repo
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: health,bus-refresh