server:
  port: 8085

spring:
  h2:
    console:
      enabled: true
      settings:
        web_allow_others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create #app실행시점에 테이블 지우고 다시 생성, 종료시 지움
    properties:
      hibernate:
        show_sql: true #System.out.pringln으로 찍음
        format_sql: true
tomcat:    
    additional-tld-skip-patterns: "*.jar"
    
logging:
  config: classpath:log4j2-spring.xml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health, beans, bus-refresh
#logging:
#  config: classpath:log4j2-local.xml
#  level:
#    org.apache.http: DEBUG
#    httpclient.wire: DEBUG


#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#  application:
#    name: service.usermanagement
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#JPA TEST를 위한 설정